### ISSUE TITLE
Linux download link not working

### ISSUE THREAD

**Issue by adevofficial** [brunurd/companion#15]
Linux download link in readme.md is not working please provide a Linux binary also

**Comment by brunurd** [comment]
Hi @adevofficial thanks for the report, and sorry for the delay, you mean that the current link in README is broken?  
If it is the case it was already fixed in the version 1.5.4. Tell me if you have the same problem again.  


Some of the next plans is use a CI automated pipeline and create a official website to turn this experience better for end users.
